services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fiskeregister-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/actuator/health",
          "||",
          "exit",
          "1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fiskeregister-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fiskeregister-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fiskeregister-network

networks:
  fiskeregister-network:
    driver: bridge
